package reports

import (
	"fmt"
	"os"
	"path/filepath"
	"time"
)

type HTMLGenerator struct {
	OutputDir string
}

func NewHTMLGenerator(outputDir string) *HTMLGenerator {
	return &HTMLGenerator{
		OutputDir: outputDir,
	}
}

func (g *HTMLGenerator) Generate(result *TestRunResult) (string, error) {
	if err := os.MkdirAll(g.OutputDir, 0755); err != nil {
		return "", fmt.Errorf("failed to create output dir: %w", err)
	}

	result.CompletedAt = time.Now()

	successRate := "0%"
	if result.TotalRules > 0 {
		successRate = fmt.Sprintf("%.1f%%", float64(result.SuccessCount)/float64(result.TotalRules)*100)
	}

	rows := ""
	for _, r := range result.Results {
		statusClass := r.Status
		if r.Status == "success" {
			statusClass = "success"
		} else {
			statusClass = "failed"
		}
		errorInfo := ""
		if r.Error != "" {
			errorInfo = fmt.Sprintf("<br><small>%s</small>", r.Error)
		}
		pcapLink := r.PCAPPath
		if r.PCAPPath != "" {
			pcapLink = fmt.Sprintf(`<a href="file://%s">%s</a>`, r.PCAPPath, filepath.Base(r.PCAPPath))
		}
		rows += fmt.Sprintf(`<tr>
			<td>%d</td>
			<td>%s</td>
			<td>%s</td>
			<td>%d</td>
			<td class="%s">%s%s</td>
			<td>%s</td>
		</tr>`, r.RuleSID, r.RuleMsg, r.Protocol, r.PacketsSent, statusClass, r.Status, errorInfo, pcapLink)
	}

	html := fmt.Sprintf(`<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Snort Rule Test Report</title>
	<style>
		body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 40px; background: #f5f5f5; }
		.container { max-width: 1200px; margin: 0 auto; }
		h1 { color: #333; }
		.summary { display: flex; gap: 20px; margin: 20px 0; }
		.card { background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); flex: 1; }
		.card h3 { margin: 0 0 10px 0; color: #666; font-size: 14px; }
		.card .value { font-size: 32px; font-weight: bold; color: #333; }
		.card.success { border-left: 4px solid #4caf50; }
		.card.failed { border-left: 4px solid #f44336; }
		.card.total { border-left: 4px solid #2196f3; }
		table { width: 100%%; border-collapse: collapse; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
		th { background: #333; color: white; padding: 12px; text-align: left; }
		td { padding: 12px; border-bottom: 1px solid #eee; }
		tr:last-child td { border-bottom: none; }
		.success { color: #4caf50; font-weight: bold; }
		.failed { color: #f44336; font-weight: bold; }
		.footer { margin-top: 20px; color: #666; font-size: 12px; text-align: center; }
	</style>
</head>
<body>
	<div class="container">
		<h1>Snort Rule Test Report</h1>
		<p>Generated: %s</p>

		<div class="summary">
			<div class="card total">
				<h3>Total Rules</h3>
				<div class="value">%d</div>
			</div>
			<div class="card success">
				<h3>Successful</h3>
				<div class="value">%d</div>
			</div>
			<div class="card failed">
				<h3>Failed</h3>
				<div class="value">%d</div>
			</div>
			<div class="card success">
				<h3>Success Rate</h3>
				<div class="value">%s</div>
			</div>
		</div>

		<h2>Test Results</h2>
		<table>
			<thead>
				<tr>
					<th>SID</th>
					<th>Message</th>
					<th>Protocol</th>
					<th>Packets Sent</th>
					<th>Status</th>
					<th>PCAP File</th>
				</tr>
			</thead>
			<tbody>
				%s
			</tbody>
		</table>

		<div class="footer">
			Generated by snortx | Test Run ID: %s
		</div>
	</div>
</body>
</html>`, result.CompletedAt.Format(time.RFC3339), result.TotalRules, result.SuccessCount, result.FailureCount, successRate, rows, result.TestRunID)

	filename := filepath.Join(g.OutputDir, fmt.Sprintf("report_%s.html", result.TestRunID))
	if err := os.WriteFile(filename, []byte(html), 0644); err != nil {
		return "", fmt.Errorf("failed to write file: %w", err)
	}

	return filename, nil
}
